name: Continuous Integration

on: [push, pull_request]

jobs:
  clang-format:
    name: Clang-Format
    runs-on: ubuntu-20.04
    steps:
      - name: Install
        run: sudo apt-get install -y clang-format
      - name: Checkout
        uses: actions/checkout@v2
      - name: Format
        run: find esp32m/ examples/ template/ -name '*.[ch]pp' | xargs clang-format -i --verbose --style=file
      - name: Diff
        run: git diff --exit-code

