name: Continuous Integration

on: [push, pull_request]

jobs:
  clang-format:
    name: Clang-Format
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: sudo apt-get install -y clang-format
      - name: Checkout
        uses: actions/checkout@v2
      - name: Format
        run: find esp32m/ examples/ template/ -name '*.[ch]pp' | xargs clang-format -i --verbose --style=file
      - name: Diff
        run: git diff --exit-code

  build-basic-example:
    name: Build example
    runs-on: ubuntu-latest
    steps:
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/.espressif
          key: ${{ runner.os }}-esp-idf
      - name: Checkout ESP-IDF
        uses: actions/checkout@v2
        with:
          repository: espressif/esp-idf
          path: esp-idf
          submodules: true
      - name: Install ESP-IDF
        run: |
         ./esp-idf/install.sh
          source ./esp-idf/export.sh
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          ls -la
          cd ./examples/basic
          python ../../esp32m.py build
